
/* ============================================ *
 * This file has been auto-generated by a tool. *
 *  In case you change anything, please be ad-  *
 * vised that the changes will not be reflected *
 * in subsequent development cycles or pull re- *
 * quests on this repository.                   *
 * ============================================ */

using System;
using System.Threading;
using System.Threading.Tasks;

namespace IX.Retry
{
    public static partial class With
    {
        /// <summary>
        /// Invokes an <see cref="System.Action"/> with a retry policy and a cancellation token.
        /// </summary>
        /// <param name="action">The action to execute with retry.</param>
        /// <param name="retryPolicy">A retry policy to apply to the action.</param>
        /// <param name="cancellationToken">The task's (optional) <see cref="System.Threading.CancellationToken"/>.</param>
        /// <returns>A <see cref="System.Threading.Tasks.Task"/> that can be awaited.</returns>
        public static Task RetryAsync(Action action, IRetryPolicy retryPolicy, CancellationToken cancellationToken = default(CancellationToken))
        {
            return action.WithRetryAsync(retryPolicy, cancellationToken);
        }

        /// <summary>
        /// Invokes an <see cref="System.Action{T}"/> with a retry policy and a cancellation token.
        /// </summary>
        /// <typeparam name="T">The action parameter type.</typeparam>
        /// <param name="action">The action to execute with retry.</param>
        /// <param name="retryPolicy">A retry policy to apply to the action.</param>
        /// <param name="arg">The action parameter, of the type specified in <typeparamref name="T"/>. This parameter is not null-checked and is forwarded directly to the action.</param>
        /// <param name="cancellationToken">The task's (optional) <see cref="System.Threading.CancellationToken"/>.</param>
        /// <returns>A <see cref="System.Threading.Tasks.Task"/> that can be awaited.</returns>
        public static Task RetryAsync<T>(Action<T> action, IRetryPolicy retryPolicy, T arg, CancellationToken cancellationToken = default(CancellationToken))
        {
            return action.WithRetryAsync(retryPolicy, arg, cancellationToken);
        }

        /// <summary>
        /// Invokes a <see cref="System.Action{T1, T2}"/> with a retry policy and a cancellation token.
        /// </summary>
        /// <typeparam name="T1">Action parameter type no. 1.</typeparam>
        /// <typeparam name="T2">Action parameter type no. 2.</typeparam>
        /// <param name="func">The action to execute with retry.</param>
        /// <param name="retryPolicy">A retry policy to apply to the function.</param>
        /// <param name="arg1">Action parameter no. 1, of the type specified in <typeparamref name="T1"/>. This parameter is not null-checked and is forwarded directly to the function.</param>
        /// <param name="arg2">Action parameter no. 2, of the type specified in <typeparamref name="T2"/>. This parameter is not null-checked and is forwarded directly to the function.</param>
        /// <param name="cancellationToken">The task's (optional) <see cref="System.Threading.CancellationToken"/>.</param>
        /// <returns>A <see cref="System.Threading.Tasks.Task"/> that can be awaited.</returns>
        public static Task RetryAsync<T1, T2>(Action<T1, T2> action, IRetryPolicy retryPolicy, T1 arg1, T2 arg2, CancellationToken cancellationToken = default(CancellationToken))
        {
            return action.WithRetryAsync(retryPolicy, arg1, arg2, cancellationToken);
        }

        /// <summary>
        /// Invokes a <see cref="System.Action{T1, T2, T3}"/> with a retry policy and a cancellation token.
        /// </summary>
        /// <typeparam name="T1">Action parameter type no. 1.</typeparam>
        /// <typeparam name="T2">Action parameter type no. 2.</typeparam>
        /// <typeparam name="T3">Action parameter type no. 3.</typeparam>
        /// <param name="func">The action to execute with retry.</param>
        /// <param name="retryPolicy">A retry policy to apply to the function.</param>
        /// <param name="arg1">Action parameter no. 1, of the type specified in <typeparamref name="T1"/>. This parameter is not null-checked and is forwarded directly to the function.</param>
        /// <param name="arg2">Action parameter no. 2, of the type specified in <typeparamref name="T2"/>. This parameter is not null-checked and is forwarded directly to the function.</param>
        /// <param name="arg3">Action parameter no. 3, of the type specified in <typeparamref name="T3"/>. This parameter is not null-checked and is forwarded directly to the function.</param>
        /// <param name="cancellationToken">The task's (optional) <see cref="System.Threading.CancellationToken"/>.</param>
        /// <returns>A <see cref="System.Threading.Tasks.Task"/> that can be awaited.</returns>
        public static Task RetryAsync<T1, T2, T3>(Action<T1, T2, T3> action, IRetryPolicy retryPolicy, T1 arg1, T2 arg2, T3 arg3, CancellationToken cancellationToken = default(CancellationToken))
        {
            return action.WithRetryAsync(retryPolicy, arg1, arg2, arg3, cancellationToken);
        }

        /// <summary>
        /// Invokes a <see cref="System.Action{T1, T2, T3, T4}"/> with a retry policy and a cancellation token.
        /// </summary>
        /// <typeparam name="T1">Action parameter type no. 1.</typeparam>
        /// <typeparam name="T2">Action parameter type no. 2.</typeparam>
        /// <typeparam name="T3">Action parameter type no. 3.</typeparam>
        /// <typeparam name="T4">Action parameter type no. 4.</typeparam>
        /// <param name="func">The action to execute with retry.</param>
        /// <param name="retryPolicy">A retry policy to apply to the function.</param>
        /// <param name="arg1">Action parameter no. 1, of the type specified in <typeparamref name="T1"/>. This parameter is not null-checked and is forwarded directly to the function.</param>
        /// <param name="arg2">Action parameter no. 2, of the type specified in <typeparamref name="T2"/>. This parameter is not null-checked and is forwarded directly to the function.</param>
        /// <param name="arg3">Action parameter no. 3, of the type specified in <typeparamref name="T3"/>. This parameter is not null-checked and is forwarded directly to the function.</param>
        /// <param name="arg4">Action parameter no. 4, of the type specified in <typeparamref name="T4"/>. This parameter is not null-checked and is forwarded directly to the function.</param>
        /// <param name="cancellationToken">The task's (optional) <see cref="System.Threading.CancellationToken"/>.</param>
        /// <returns>A <see cref="System.Threading.Tasks.Task"/> that can be awaited.</returns>
        public static Task RetryAsync<T1, T2, T3, T4>(Action<T1, T2, T3, T4> action, IRetryPolicy retryPolicy, T1 arg1, T2 arg2, T3 arg3, T4 arg4, CancellationToken cancellationToken = default(CancellationToken))
        {
            return action.WithRetryAsync(retryPolicy, arg1, arg2, arg3, arg4, cancellationToken);
        }

        /// <summary>
        /// Invokes a <see cref="System.Action{T1, T2, T3, T4, T5}"/> with a retry policy and a cancellation token.
        /// </summary>
        /// <typeparam name="T1">Action parameter type no. 1.</typeparam>
        /// <typeparam name="T2">Action parameter type no. 2.</typeparam>
        /// <typeparam name="T3">Action parameter type no. 3.</typeparam>
        /// <typeparam name="T4">Action parameter type no. 4.</typeparam>
        /// <typeparam name="T5">Action parameter type no. 5.</typeparam>
        /// <param name="func">The action to execute with retry.</param>
        /// <param name="retryPolicy">A retry policy to apply to the function.</param>
        /// <param name="arg1">Action parameter no. 1, of the type specified in <typeparamref name="T1"/>. This parameter is not null-checked and is forwarded directly to the function.</param>
        /// <param name="arg2">Action parameter no. 2, of the type specified in <typeparamref name="T2"/>. This parameter is not null-checked and is forwarded directly to the function.</param>
        /// <param name="arg3">Action parameter no. 3, of the type specified in <typeparamref name="T3"/>. This parameter is not null-checked and is forwarded directly to the function.</param>
        /// <param name="arg4">Action parameter no. 4, of the type specified in <typeparamref name="T4"/>. This parameter is not null-checked and is forwarded directly to the function.</param>
        /// <param name="arg5">Action parameter no. 5, of the type specified in <typeparamref name="T5"/>. This parameter is not null-checked and is forwarded directly to the function.</param>
        /// <param name="cancellationToken">The task's (optional) <see cref="System.Threading.CancellationToken"/>.</param>
        /// <returns>A <see cref="System.Threading.Tasks.Task"/> that can be awaited.</returns>
        public static Task RetryAsync<T1, T2, T3, T4, T5>(Action<T1, T2, T3, T4, T5> action, IRetryPolicy retryPolicy, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, CancellationToken cancellationToken = default(CancellationToken))
        {
            return action.WithRetryAsync(retryPolicy, arg1, arg2, arg3, arg4, arg5, cancellationToken);
        }

        /// <summary>
        /// Invokes a <see cref="System.Action{T1, T2, T3, T4, T5, T6}"/> with a retry policy and a cancellation token.
        /// </summary>
        /// <typeparam name="T1">Action parameter type no. 1.</typeparam>
        /// <typeparam name="T2">Action parameter type no. 2.</typeparam>
        /// <typeparam name="T3">Action parameter type no. 3.</typeparam>
        /// <typeparam name="T4">Action parameter type no. 4.</typeparam>
        /// <typeparam name="T5">Action parameter type no. 5.</typeparam>
        /// <typeparam name="T6">Action parameter type no. 6.</typeparam>
        /// <param name="func">The action to execute with retry.</param>
        /// <param name="retryPolicy">A retry policy to apply to the function.</param>
        /// <param name="arg1">Action parameter no. 1, of the type specified in <typeparamref name="T1"/>. This parameter is not null-checked and is forwarded directly to the function.</param>
        /// <param name="arg2">Action parameter no. 2, of the type specified in <typeparamref name="T2"/>. This parameter is not null-checked and is forwarded directly to the function.</param>
        /// <param name="arg3">Action parameter no. 3, of the type specified in <typeparamref name="T3"/>. This parameter is not null-checked and is forwarded directly to the function.</param>
        /// <param name="arg4">Action parameter no. 4, of the type specified in <typeparamref name="T4"/>. This parameter is not null-checked and is forwarded directly to the function.</param>
        /// <param name="arg5">Action parameter no. 5, of the type specified in <typeparamref name="T5"/>. This parameter is not null-checked and is forwarded directly to the function.</param>
        /// <param name="arg6">Action parameter no. 6, of the type specified in <typeparamref name="T6"/>. This parameter is not null-checked and is forwarded directly to the function.</param>
        /// <param name="cancellationToken">The task's (optional) <see cref="System.Threading.CancellationToken"/>.</param>
        /// <returns>A <see cref="System.Threading.Tasks.Task"/> that can be awaited.</returns>
        public static Task RetryAsync<T1, T2, T3, T4, T5, T6>(Action<T1, T2, T3, T4, T5, T6> action, IRetryPolicy retryPolicy, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6, CancellationToken cancellationToken = default(CancellationToken))
        {
            return action.WithRetryAsync(retryPolicy, arg1, arg2, arg3, arg4, arg5, arg6, cancellationToken);
        }

        /// <summary>
        /// Invokes a <see cref="System.Action{T1, T2, T3, T4, T5, T6, T7}"/> with a retry policy and a cancellation token.
        /// </summary>
        /// <typeparam name="T1">Action parameter type no. 1.</typeparam>
        /// <typeparam name="T2">Action parameter type no. 2.</typeparam>
        /// <typeparam name="T3">Action parameter type no. 3.</typeparam>
        /// <typeparam name="T4">Action parameter type no. 4.</typeparam>
        /// <typeparam name="T5">Action parameter type no. 5.</typeparam>
        /// <typeparam name="T6">Action parameter type no. 6.</typeparam>
        /// <typeparam name="T7">Action parameter type no. 7.</typeparam>
        /// <param name="func">The action to execute with retry.</param>
        /// <param name="retryPolicy">A retry policy to apply to the function.</param>
        /// <param name="arg1">Action parameter no. 1, of the type specified in <typeparamref name="T1"/>. This parameter is not null-checked and is forwarded directly to the function.</param>
        /// <param name="arg2">Action parameter no. 2, of the type specified in <typeparamref name="T2"/>. This parameter is not null-checked and is forwarded directly to the function.</param>
        /// <param name="arg3">Action parameter no. 3, of the type specified in <typeparamref name="T3"/>. This parameter is not null-checked and is forwarded directly to the function.</param>
        /// <param name="arg4">Action parameter no. 4, of the type specified in <typeparamref name="T4"/>. This parameter is not null-checked and is forwarded directly to the function.</param>
        /// <param name="arg5">Action parameter no. 5, of the type specified in <typeparamref name="T5"/>. This parameter is not null-checked and is forwarded directly to the function.</param>
        /// <param name="arg6">Action parameter no. 6, of the type specified in <typeparamref name="T6"/>. This parameter is not null-checked and is forwarded directly to the function.</param>
        /// <param name="arg7">Action parameter no. 7, of the type specified in <typeparamref name="T7"/>. This parameter is not null-checked and is forwarded directly to the function.</param>
        /// <param name="cancellationToken">The task's (optional) <see cref="System.Threading.CancellationToken"/>.</param>
        /// <returns>A <see cref="System.Threading.Tasks.Task"/> that can be awaited.</returns>
        public static Task RetryAsync<T1, T2, T3, T4, T5, T6, T7>(Action<T1, T2, T3, T4, T5, T6, T7> action, IRetryPolicy retryPolicy, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6, T7 arg7, CancellationToken cancellationToken = default(CancellationToken))
        {
            return action.WithRetryAsync(retryPolicy, arg1, arg2, arg3, arg4, arg5, arg6, arg7, cancellationToken);
        }

        /// <summary>
        /// Invokes a <see cref="System.Action{T1, T2, T3, T4, T5, T6, T7, T8}"/> with a retry policy and a cancellation token.
        /// </summary>
        /// <typeparam name="T1">Action parameter type no. 1.</typeparam>
        /// <typeparam name="T2">Action parameter type no. 2.</typeparam>
        /// <typeparam name="T3">Action parameter type no. 3.</typeparam>
        /// <typeparam name="T4">Action parameter type no. 4.</typeparam>
        /// <typeparam name="T5">Action parameter type no. 5.</typeparam>
        /// <typeparam name="T6">Action parameter type no. 6.</typeparam>
        /// <typeparam name="T7">Action parameter type no. 7.</typeparam>
        /// <typeparam name="T8">Action parameter type no. 8.</typeparam>
        /// <param name="func">The action to execute with retry.</param>
        /// <param name="retryPolicy">A retry policy to apply to the function.</param>
        /// <param name="arg1">Action parameter no. 1, of the type specified in <typeparamref name="T1"/>. This parameter is not null-checked and is forwarded directly to the function.</param>
        /// <param name="arg2">Action parameter no. 2, of the type specified in <typeparamref name="T2"/>. This parameter is not null-checked and is forwarded directly to the function.</param>
        /// <param name="arg3">Action parameter no. 3, of the type specified in <typeparamref name="T3"/>. This parameter is not null-checked and is forwarded directly to the function.</param>
        /// <param name="arg4">Action parameter no. 4, of the type specified in <typeparamref name="T4"/>. This parameter is not null-checked and is forwarded directly to the function.</param>
        /// <param name="arg5">Action parameter no. 5, of the type specified in <typeparamref name="T5"/>. This parameter is not null-checked and is forwarded directly to the function.</param>
        /// <param name="arg6">Action parameter no. 6, of the type specified in <typeparamref name="T6"/>. This parameter is not null-checked and is forwarded directly to the function.</param>
        /// <param name="arg7">Action parameter no. 7, of the type specified in <typeparamref name="T7"/>. This parameter is not null-checked and is forwarded directly to the function.</param>
        /// <param name="arg8">Action parameter no. 8, of the type specified in <typeparamref name="T8"/>. This parameter is not null-checked and is forwarded directly to the function.</param>
        /// <param name="cancellationToken">The task's (optional) <see cref="System.Threading.CancellationToken"/>.</param>
        /// <returns>A <see cref="System.Threading.Tasks.Task"/> that can be awaited.</returns>
        public static Task RetryAsync<T1, T2, T3, T4, T5, T6, T7, T8>(Action<T1, T2, T3, T4, T5, T6, T7, T8> action, IRetryPolicy retryPolicy, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6, T7 arg7, T8 arg8, CancellationToken cancellationToken = default(CancellationToken))
        {
            return action.WithRetryAsync(retryPolicy, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, cancellationToken);
        }

        /// <summary>
        /// Invokes a <see cref="System.Action{T1, T2, T3, T4, T5, T6, T7, T8, T9}"/> with a retry policy and a cancellation token.
        /// </summary>
        /// <typeparam name="T1">Action parameter type no. 1.</typeparam>
        /// <typeparam name="T2">Action parameter type no. 2.</typeparam>
        /// <typeparam name="T3">Action parameter type no. 3.</typeparam>
        /// <typeparam name="T4">Action parameter type no. 4.</typeparam>
        /// <typeparam name="T5">Action parameter type no. 5.</typeparam>
        /// <typeparam name="T6">Action parameter type no. 6.</typeparam>
        /// <typeparam name="T7">Action parameter type no. 7.</typeparam>
        /// <typeparam name="T8">Action parameter type no. 8.</typeparam>
        /// <typeparam name="T9">Action parameter type no. 9.</typeparam>
        /// <param name="func">The action to execute with retry.</param>
        /// <param name="retryPolicy">A retry policy to apply to the function.</param>
        /// <param name="arg1">Action parameter no. 1, of the type specified in <typeparamref name="T1"/>. This parameter is not null-checked and is forwarded directly to the function.</param>
        /// <param name="arg2">Action parameter no. 2, of the type specified in <typeparamref name="T2"/>. This parameter is not null-checked and is forwarded directly to the function.</param>
        /// <param name="arg3">Action parameter no. 3, of the type specified in <typeparamref name="T3"/>. This parameter is not null-checked and is forwarded directly to the function.</param>
        /// <param name="arg4">Action parameter no. 4, of the type specified in <typeparamref name="T4"/>. This parameter is not null-checked and is forwarded directly to the function.</param>
        /// <param name="arg5">Action parameter no. 5, of the type specified in <typeparamref name="T5"/>. This parameter is not null-checked and is forwarded directly to the function.</param>
        /// <param name="arg6">Action parameter no. 6, of the type specified in <typeparamref name="T6"/>. This parameter is not null-checked and is forwarded directly to the function.</param>
        /// <param name="arg7">Action parameter no. 7, of the type specified in <typeparamref name="T7"/>. This parameter is not null-checked and is forwarded directly to the function.</param>
        /// <param name="arg8">Action parameter no. 8, of the type specified in <typeparamref name="T8"/>. This parameter is not null-checked and is forwarded directly to the function.</param>
        /// <param name="arg9">Action parameter no. 9, of the type specified in <typeparamref name="T9"/>. This parameter is not null-checked and is forwarded directly to the function.</param>
        /// <param name="cancellationToken">The task's (optional) <see cref="System.Threading.CancellationToken"/>.</param>
        /// <returns>A <see cref="System.Threading.Tasks.Task"/> that can be awaited.</returns>
        public static Task RetryAsync<T1, T2, T3, T4, T5, T6, T7, T8, T9>(Action<T1, T2, T3, T4, T5, T6, T7, T8, T9> action, IRetryPolicy retryPolicy, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6, T7 arg7, T8 arg8, T9 arg9, CancellationToken cancellationToken = default(CancellationToken))
        {
            return action.WithRetryAsync(retryPolicy, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, cancellationToken);
        }

        /// <summary>
        /// Invokes a <see cref="System.Action{T1, T2, T3, T4, T5, T6, T7, T8, T9, T10}"/> with a retry policy and a cancellation token.
        /// </summary>
        /// <typeparam name="T1">Action parameter type no. 1.</typeparam>
        /// <typeparam name="T2">Action parameter type no. 2.</typeparam>
        /// <typeparam name="T3">Action parameter type no. 3.</typeparam>
        /// <typeparam name="T4">Action parameter type no. 4.</typeparam>
        /// <typeparam name="T5">Action parameter type no. 5.</typeparam>
        /// <typeparam name="T6">Action parameter type no. 6.</typeparam>
        /// <typeparam name="T7">Action parameter type no. 7.</typeparam>
        /// <typeparam name="T8">Action parameter type no. 8.</typeparam>
        /// <typeparam name="T9">Action parameter type no. 9.</typeparam>
        /// <typeparam name="T10">Action parameter type no. 10.</typeparam>
        /// <param name="func">The action to execute with retry.</param>
        /// <param name="retryPolicy">A retry policy to apply to the function.</param>
        /// <param name="arg1">Action parameter no. 1, of the type specified in <typeparamref name="T1"/>. This parameter is not null-checked and is forwarded directly to the function.</param>
        /// <param name="arg2">Action parameter no. 2, of the type specified in <typeparamref name="T2"/>. This parameter is not null-checked and is forwarded directly to the function.</param>
        /// <param name="arg3">Action parameter no. 3, of the type specified in <typeparamref name="T3"/>. This parameter is not null-checked and is forwarded directly to the function.</param>
        /// <param name="arg4">Action parameter no. 4, of the type specified in <typeparamref name="T4"/>. This parameter is not null-checked and is forwarded directly to the function.</param>
        /// <param name="arg5">Action parameter no. 5, of the type specified in <typeparamref name="T5"/>. This parameter is not null-checked and is forwarded directly to the function.</param>
        /// <param name="arg6">Action parameter no. 6, of the type specified in <typeparamref name="T6"/>. This parameter is not null-checked and is forwarded directly to the function.</param>
        /// <param name="arg7">Action parameter no. 7, of the type specified in <typeparamref name="T7"/>. This parameter is not null-checked and is forwarded directly to the function.</param>
        /// <param name="arg8">Action parameter no. 8, of the type specified in <typeparamref name="T8"/>. This parameter is not null-checked and is forwarded directly to the function.</param>
        /// <param name="arg9">Action parameter no. 9, of the type specified in <typeparamref name="T9"/>. This parameter is not null-checked and is forwarded directly to the function.</param>
        /// <param name="arg10">Action parameter no. 10, of the type specified in <typeparamref name="T10"/>. This parameter is not null-checked and is forwarded directly to the function.</param>
        /// <param name="cancellationToken">The task's (optional) <see cref="System.Threading.CancellationToken"/>.</param>
        /// <returns>A <see cref="System.Threading.Tasks.Task"/> that can be awaited.</returns>
        public static Task RetryAsync<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10>(Action<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10> action, IRetryPolicy retryPolicy, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6, T7 arg7, T8 arg8, T9 arg9, T10 arg10, CancellationToken cancellationToken = default(CancellationToken))
        {
            return action.WithRetryAsync(retryPolicy, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, cancellationToken);
        }

        /// <summary>
        /// Invokes a <see cref="System.Action{T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11}"/> with a retry policy and a cancellation token.
        /// </summary>
        /// <typeparam name="T1">Action parameter type no. 1.</typeparam>
        /// <typeparam name="T2">Action parameter type no. 2.</typeparam>
        /// <typeparam name="T3">Action parameter type no. 3.</typeparam>
        /// <typeparam name="T4">Action parameter type no. 4.</typeparam>
        /// <typeparam name="T5">Action parameter type no. 5.</typeparam>
        /// <typeparam name="T6">Action parameter type no. 6.</typeparam>
        /// <typeparam name="T7">Action parameter type no. 7.</typeparam>
        /// <typeparam name="T8">Action parameter type no. 8.</typeparam>
        /// <typeparam name="T9">Action parameter type no. 9.</typeparam>
        /// <typeparam name="T10">Action parameter type no. 10.</typeparam>
        /// <typeparam name="T11">Action parameter type no. 11.</typeparam>
        /// <param name="func">The action to execute with retry.</param>
        /// <param name="retryPolicy">A retry policy to apply to the function.</param>
        /// <param name="arg1">Action parameter no. 1, of the type specified in <typeparamref name="T1"/>. This parameter is not null-checked and is forwarded directly to the function.</param>
        /// <param name="arg2">Action parameter no. 2, of the type specified in <typeparamref name="T2"/>. This parameter is not null-checked and is forwarded directly to the function.</param>
        /// <param name="arg3">Action parameter no. 3, of the type specified in <typeparamref name="T3"/>. This parameter is not null-checked and is forwarded directly to the function.</param>
        /// <param name="arg4">Action parameter no. 4, of the type specified in <typeparamref name="T4"/>. This parameter is not null-checked and is forwarded directly to the function.</param>
        /// <param name="arg5">Action parameter no. 5, of the type specified in <typeparamref name="T5"/>. This parameter is not null-checked and is forwarded directly to the function.</param>
        /// <param name="arg6">Action parameter no. 6, of the type specified in <typeparamref name="T6"/>. This parameter is not null-checked and is forwarded directly to the function.</param>
        /// <param name="arg7">Action parameter no. 7, of the type specified in <typeparamref name="T7"/>. This parameter is not null-checked and is forwarded directly to the function.</param>
        /// <param name="arg8">Action parameter no. 8, of the type specified in <typeparamref name="T8"/>. This parameter is not null-checked and is forwarded directly to the function.</param>
        /// <param name="arg9">Action parameter no. 9, of the type specified in <typeparamref name="T9"/>. This parameter is not null-checked and is forwarded directly to the function.</param>
        /// <param name="arg10">Action parameter no. 10, of the type specified in <typeparamref name="T10"/>. This parameter is not null-checked and is forwarded directly to the function.</param>
        /// <param name="arg11">Action parameter no. 11, of the type specified in <typeparamref name="T11"/>. This parameter is not null-checked and is forwarded directly to the function.</param>
        /// <param name="cancellationToken">The task's (optional) <see cref="System.Threading.CancellationToken"/>.</param>
        /// <returns>A <see cref="System.Threading.Tasks.Task"/> that can be awaited.</returns>
        public static Task RetryAsync<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11>(Action<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11> action, IRetryPolicy retryPolicy, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6, T7 arg7, T8 arg8, T9 arg9, T10 arg10, T11 arg11, CancellationToken cancellationToken = default(CancellationToken))
        {
            return action.WithRetryAsync(retryPolicy, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, cancellationToken);
        }

        /// <summary>
        /// Invokes a <see cref="System.Action{T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12}"/> with a retry policy and a cancellation token.
        /// </summary>
        /// <typeparam name="T1">Action parameter type no. 1.</typeparam>
        /// <typeparam name="T2">Action parameter type no. 2.</typeparam>
        /// <typeparam name="T3">Action parameter type no. 3.</typeparam>
        /// <typeparam name="T4">Action parameter type no. 4.</typeparam>
        /// <typeparam name="T5">Action parameter type no. 5.</typeparam>
        /// <typeparam name="T6">Action parameter type no. 6.</typeparam>
        /// <typeparam name="T7">Action parameter type no. 7.</typeparam>
        /// <typeparam name="T8">Action parameter type no. 8.</typeparam>
        /// <typeparam name="T9">Action parameter type no. 9.</typeparam>
        /// <typeparam name="T10">Action parameter type no. 10.</typeparam>
        /// <typeparam name="T11">Action parameter type no. 11.</typeparam>
        /// <typeparam name="T12">Action parameter type no. 12.</typeparam>
        /// <param name="func">The action to execute with retry.</param>
        /// <param name="retryPolicy">A retry policy to apply to the function.</param>
        /// <param name="arg1">Action parameter no. 1, of the type specified in <typeparamref name="T1"/>. This parameter is not null-checked and is forwarded directly to the function.</param>
        /// <param name="arg2">Action parameter no. 2, of the type specified in <typeparamref name="T2"/>. This parameter is not null-checked and is forwarded directly to the function.</param>
        /// <param name="arg3">Action parameter no. 3, of the type specified in <typeparamref name="T3"/>. This parameter is not null-checked and is forwarded directly to the function.</param>
        /// <param name="arg4">Action parameter no. 4, of the type specified in <typeparamref name="T4"/>. This parameter is not null-checked and is forwarded directly to the function.</param>
        /// <param name="arg5">Action parameter no. 5, of the type specified in <typeparamref name="T5"/>. This parameter is not null-checked and is forwarded directly to the function.</param>
        /// <param name="arg6">Action parameter no. 6, of the type specified in <typeparamref name="T6"/>. This parameter is not null-checked and is forwarded directly to the function.</param>
        /// <param name="arg7">Action parameter no. 7, of the type specified in <typeparamref name="T7"/>. This parameter is not null-checked and is forwarded directly to the function.</param>
        /// <param name="arg8">Action parameter no. 8, of the type specified in <typeparamref name="T8"/>. This parameter is not null-checked and is forwarded directly to the function.</param>
        /// <param name="arg9">Action parameter no. 9, of the type specified in <typeparamref name="T9"/>. This parameter is not null-checked and is forwarded directly to the function.</param>
        /// <param name="arg10">Action parameter no. 10, of the type specified in <typeparamref name="T10"/>. This parameter is not null-checked and is forwarded directly to the function.</param>
        /// <param name="arg11">Action parameter no. 11, of the type specified in <typeparamref name="T11"/>. This parameter is not null-checked and is forwarded directly to the function.</param>
        /// <param name="arg12">Action parameter no. 12, of the type specified in <typeparamref name="T12"/>. This parameter is not null-checked and is forwarded directly to the function.</param>
        /// <param name="cancellationToken">The task's (optional) <see cref="System.Threading.CancellationToken"/>.</param>
        /// <returns>A <see cref="System.Threading.Tasks.Task"/> that can be awaited.</returns>
        public static Task RetryAsync<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12>(Action<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12> action, IRetryPolicy retryPolicy, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6, T7 arg7, T8 arg8, T9 arg9, T10 arg10, T11 arg11, T12 arg12, CancellationToken cancellationToken = default(CancellationToken))
        {
            return action.WithRetryAsync(retryPolicy, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, cancellationToken);
        }

        /// <summary>
        /// Invokes a <see cref="System.Action{T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13}"/> with a retry policy and a cancellation token.
        /// </summary>
        /// <typeparam name="T1">Action parameter type no. 1.</typeparam>
        /// <typeparam name="T2">Action parameter type no. 2.</typeparam>
        /// <typeparam name="T3">Action parameter type no. 3.</typeparam>
        /// <typeparam name="T4">Action parameter type no. 4.</typeparam>
        /// <typeparam name="T5">Action parameter type no. 5.</typeparam>
        /// <typeparam name="T6">Action parameter type no. 6.</typeparam>
        /// <typeparam name="T7">Action parameter type no. 7.</typeparam>
        /// <typeparam name="T8">Action parameter type no. 8.</typeparam>
        /// <typeparam name="T9">Action parameter type no. 9.</typeparam>
        /// <typeparam name="T10">Action parameter type no. 10.</typeparam>
        /// <typeparam name="T11">Action parameter type no. 11.</typeparam>
        /// <typeparam name="T12">Action parameter type no. 12.</typeparam>
        /// <typeparam name="T13">Action parameter type no. 13.</typeparam>
        /// <param name="func">The action to execute with retry.</param>
        /// <param name="retryPolicy">A retry policy to apply to the function.</param>
        /// <param name="arg1">Action parameter no. 1, of the type specified in <typeparamref name="T1"/>. This parameter is not null-checked and is forwarded directly to the function.</param>
        /// <param name="arg2">Action parameter no. 2, of the type specified in <typeparamref name="T2"/>. This parameter is not null-checked and is forwarded directly to the function.</param>
        /// <param name="arg3">Action parameter no. 3, of the type specified in <typeparamref name="T3"/>. This parameter is not null-checked and is forwarded directly to the function.</param>
        /// <param name="arg4">Action parameter no. 4, of the type specified in <typeparamref name="T4"/>. This parameter is not null-checked and is forwarded directly to the function.</param>
        /// <param name="arg5">Action parameter no. 5, of the type specified in <typeparamref name="T5"/>. This parameter is not null-checked and is forwarded directly to the function.</param>
        /// <param name="arg6">Action parameter no. 6, of the type specified in <typeparamref name="T6"/>. This parameter is not null-checked and is forwarded directly to the function.</param>
        /// <param name="arg7">Action parameter no. 7, of the type specified in <typeparamref name="T7"/>. This parameter is not null-checked and is forwarded directly to the function.</param>
        /// <param name="arg8">Action parameter no. 8, of the type specified in <typeparamref name="T8"/>. This parameter is not null-checked and is forwarded directly to the function.</param>
        /// <param name="arg9">Action parameter no. 9, of the type specified in <typeparamref name="T9"/>. This parameter is not null-checked and is forwarded directly to the function.</param>
        /// <param name="arg10">Action parameter no. 10, of the type specified in <typeparamref name="T10"/>. This parameter is not null-checked and is forwarded directly to the function.</param>
        /// <param name="arg11">Action parameter no. 11, of the type specified in <typeparamref name="T11"/>. This parameter is not null-checked and is forwarded directly to the function.</param>
        /// <param name="arg12">Action parameter no. 12, of the type specified in <typeparamref name="T12"/>. This parameter is not null-checked and is forwarded directly to the function.</param>
        /// <param name="arg13">Action parameter no. 13, of the type specified in <typeparamref name="T13"/>. This parameter is not null-checked and is forwarded directly to the function.</param>
        /// <param name="cancellationToken">The task's (optional) <see cref="System.Threading.CancellationToken"/>.</param>
        /// <returns>A <see cref="System.Threading.Tasks.Task"/> that can be awaited.</returns>
        public static Task RetryAsync<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13>(Action<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13> action, IRetryPolicy retryPolicy, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6, T7 arg7, T8 arg8, T9 arg9, T10 arg10, T11 arg11, T12 arg12, T13 arg13, CancellationToken cancellationToken = default(CancellationToken))
        {
            return action.WithRetryAsync(retryPolicy, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, cancellationToken);
        }

        /// <summary>
        /// Invokes a <see cref="System.Action{T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14}"/> with a retry policy and a cancellation token.
        /// </summary>
        /// <typeparam name="T1">Action parameter type no. 1.</typeparam>
        /// <typeparam name="T2">Action parameter type no. 2.</typeparam>
        /// <typeparam name="T3">Action parameter type no. 3.</typeparam>
        /// <typeparam name="T4">Action parameter type no. 4.</typeparam>
        /// <typeparam name="T5">Action parameter type no. 5.</typeparam>
        /// <typeparam name="T6">Action parameter type no. 6.</typeparam>
        /// <typeparam name="T7">Action parameter type no. 7.</typeparam>
        /// <typeparam name="T8">Action parameter type no. 8.</typeparam>
        /// <typeparam name="T9">Action parameter type no. 9.</typeparam>
        /// <typeparam name="T10">Action parameter type no. 10.</typeparam>
        /// <typeparam name="T11">Action parameter type no. 11.</typeparam>
        /// <typeparam name="T12">Action parameter type no. 12.</typeparam>
        /// <typeparam name="T13">Action parameter type no. 13.</typeparam>
        /// <typeparam name="T14">Action parameter type no. 14.</typeparam>
        /// <param name="func">The action to execute with retry.</param>
        /// <param name="retryPolicy">A retry policy to apply to the function.</param>
        /// <param name="arg1">Action parameter no. 1, of the type specified in <typeparamref name="T1"/>. This parameter is not null-checked and is forwarded directly to the function.</param>
        /// <param name="arg2">Action parameter no. 2, of the type specified in <typeparamref name="T2"/>. This parameter is not null-checked and is forwarded directly to the function.</param>
        /// <param name="arg3">Action parameter no. 3, of the type specified in <typeparamref name="T3"/>. This parameter is not null-checked and is forwarded directly to the function.</param>
        /// <param name="arg4">Action parameter no. 4, of the type specified in <typeparamref name="T4"/>. This parameter is not null-checked and is forwarded directly to the function.</param>
        /// <param name="arg5">Action parameter no. 5, of the type specified in <typeparamref name="T5"/>. This parameter is not null-checked and is forwarded directly to the function.</param>
        /// <param name="arg6">Action parameter no. 6, of the type specified in <typeparamref name="T6"/>. This parameter is not null-checked and is forwarded directly to the function.</param>
        /// <param name="arg7">Action parameter no. 7, of the type specified in <typeparamref name="T7"/>. This parameter is not null-checked and is forwarded directly to the function.</param>
        /// <param name="arg8">Action parameter no. 8, of the type specified in <typeparamref name="T8"/>. This parameter is not null-checked and is forwarded directly to the function.</param>
        /// <param name="arg9">Action parameter no. 9, of the type specified in <typeparamref name="T9"/>. This parameter is not null-checked and is forwarded directly to the function.</param>
        /// <param name="arg10">Action parameter no. 10, of the type specified in <typeparamref name="T10"/>. This parameter is not null-checked and is forwarded directly to the function.</param>
        /// <param name="arg11">Action parameter no. 11, of the type specified in <typeparamref name="T11"/>. This parameter is not null-checked and is forwarded directly to the function.</param>
        /// <param name="arg12">Action parameter no. 12, of the type specified in <typeparamref name="T12"/>. This parameter is not null-checked and is forwarded directly to the function.</param>
        /// <param name="arg13">Action parameter no. 13, of the type specified in <typeparamref name="T13"/>. This parameter is not null-checked and is forwarded directly to the function.</param>
        /// <param name="arg14">Action parameter no. 14, of the type specified in <typeparamref name="T14"/>. This parameter is not null-checked and is forwarded directly to the function.</param>
        /// <param name="cancellationToken">The task's (optional) <see cref="System.Threading.CancellationToken"/>.</param>
        /// <returns>A <see cref="System.Threading.Tasks.Task"/> that can be awaited.</returns>
        public static Task RetryAsync<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14>(Action<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14> action, IRetryPolicy retryPolicy, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6, T7 arg7, T8 arg8, T9 arg9, T10 arg10, T11 arg11, T12 arg12, T13 arg13, T14 arg14, CancellationToken cancellationToken = default(CancellationToken))
        {
            return action.WithRetryAsync(retryPolicy, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14, cancellationToken);
        }

        /// <summary>
        /// Invokes a <see cref="System.Action{T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15}"/> with a retry policy and a cancellation token.
        /// </summary>
        /// <typeparam name="T1">Action parameter type no. 1.</typeparam>
        /// <typeparam name="T2">Action parameter type no. 2.</typeparam>
        /// <typeparam name="T3">Action parameter type no. 3.</typeparam>
        /// <typeparam name="T4">Action parameter type no. 4.</typeparam>
        /// <typeparam name="T5">Action parameter type no. 5.</typeparam>
        /// <typeparam name="T6">Action parameter type no. 6.</typeparam>
        /// <typeparam name="T7">Action parameter type no. 7.</typeparam>
        /// <typeparam name="T8">Action parameter type no. 8.</typeparam>
        /// <typeparam name="T9">Action parameter type no. 9.</typeparam>
        /// <typeparam name="T10">Action parameter type no. 10.</typeparam>
        /// <typeparam name="T11">Action parameter type no. 11.</typeparam>
        /// <typeparam name="T12">Action parameter type no. 12.</typeparam>
        /// <typeparam name="T13">Action parameter type no. 13.</typeparam>
        /// <typeparam name="T14">Action parameter type no. 14.</typeparam>
        /// <typeparam name="T15">Action parameter type no. 15.</typeparam>
        /// <param name="func">The action to execute with retry.</param>
        /// <param name="retryPolicy">A retry policy to apply to the function.</param>
        /// <param name="arg1">Action parameter no. 1, of the type specified in <typeparamref name="T1"/>. This parameter is not null-checked and is forwarded directly to the function.</param>
        /// <param name="arg2">Action parameter no. 2, of the type specified in <typeparamref name="T2"/>. This parameter is not null-checked and is forwarded directly to the function.</param>
        /// <param name="arg3">Action parameter no. 3, of the type specified in <typeparamref name="T3"/>. This parameter is not null-checked and is forwarded directly to the function.</param>
        /// <param name="arg4">Action parameter no. 4, of the type specified in <typeparamref name="T4"/>. This parameter is not null-checked and is forwarded directly to the function.</param>
        /// <param name="arg5">Action parameter no. 5, of the type specified in <typeparamref name="T5"/>. This parameter is not null-checked and is forwarded directly to the function.</param>
        /// <param name="arg6">Action parameter no. 6, of the type specified in <typeparamref name="T6"/>. This parameter is not null-checked and is forwarded directly to the function.</param>
        /// <param name="arg7">Action parameter no. 7, of the type specified in <typeparamref name="T7"/>. This parameter is not null-checked and is forwarded directly to the function.</param>
        /// <param name="arg8">Action parameter no. 8, of the type specified in <typeparamref name="T8"/>. This parameter is not null-checked and is forwarded directly to the function.</param>
        /// <param name="arg9">Action parameter no. 9, of the type specified in <typeparamref name="T9"/>. This parameter is not null-checked and is forwarded directly to the function.</param>
        /// <param name="arg10">Action parameter no. 10, of the type specified in <typeparamref name="T10"/>. This parameter is not null-checked and is forwarded directly to the function.</param>
        /// <param name="arg11">Action parameter no. 11, of the type specified in <typeparamref name="T11"/>. This parameter is not null-checked and is forwarded directly to the function.</param>
        /// <param name="arg12">Action parameter no. 12, of the type specified in <typeparamref name="T12"/>. This parameter is not null-checked and is forwarded directly to the function.</param>
        /// <param name="arg13">Action parameter no. 13, of the type specified in <typeparamref name="T13"/>. This parameter is not null-checked and is forwarded directly to the function.</param>
        /// <param name="arg14">Action parameter no. 14, of the type specified in <typeparamref name="T14"/>. This parameter is not null-checked and is forwarded directly to the function.</param>
        /// <param name="arg15">Action parameter no. 15, of the type specified in <typeparamref name="T15"/>. This parameter is not null-checked and is forwarded directly to the function.</param>
        /// <param name="cancellationToken">The task's (optional) <see cref="System.Threading.CancellationToken"/>.</param>
        /// <returns>A <see cref="System.Threading.Tasks.Task"/> that can be awaited.</returns>
        public static Task RetryAsync<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15>(Action<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15> action, IRetryPolicy retryPolicy, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6, T7 arg7, T8 arg8, T9 arg9, T10 arg10, T11 arg11, T12 arg12, T13 arg13, T14 arg14, T15 arg15, CancellationToken cancellationToken = default(CancellationToken))
        {
            return action.WithRetryAsync(retryPolicy, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14, arg15, cancellationToken);
        }

        /// <summary>
        /// Invokes a <see cref="System.Action{T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16}"/> with a retry policy and a cancellation token.
        /// </summary>
        /// <typeparam name="T1">Action parameter type no. 1.</typeparam>
        /// <typeparam name="T2">Action parameter type no. 2.</typeparam>
        /// <typeparam name="T3">Action parameter type no. 3.</typeparam>
        /// <typeparam name="T4">Action parameter type no. 4.</typeparam>
        /// <typeparam name="T5">Action parameter type no. 5.</typeparam>
        /// <typeparam name="T6">Action parameter type no. 6.</typeparam>
        /// <typeparam name="T7">Action parameter type no. 7.</typeparam>
        /// <typeparam name="T8">Action parameter type no. 8.</typeparam>
        /// <typeparam name="T9">Action parameter type no. 9.</typeparam>
        /// <typeparam name="T10">Action parameter type no. 10.</typeparam>
        /// <typeparam name="T11">Action parameter type no. 11.</typeparam>
        /// <typeparam name="T12">Action parameter type no. 12.</typeparam>
        /// <typeparam name="T13">Action parameter type no. 13.</typeparam>
        /// <typeparam name="T14">Action parameter type no. 14.</typeparam>
        /// <typeparam name="T15">Action parameter type no. 15.</typeparam>
        /// <typeparam name="T16">Action parameter type no. 16.</typeparam>
        /// <param name="func">The action to execute with retry.</param>
        /// <param name="retryPolicy">A retry policy to apply to the function.</param>
        /// <param name="arg1">Action parameter no. 1, of the type specified in <typeparamref name="T1"/>. This parameter is not null-checked and is forwarded directly to the function.</param>
        /// <param name="arg2">Action parameter no. 2, of the type specified in <typeparamref name="T2"/>. This parameter is not null-checked and is forwarded directly to the function.</param>
        /// <param name="arg3">Action parameter no. 3, of the type specified in <typeparamref name="T3"/>. This parameter is not null-checked and is forwarded directly to the function.</param>
        /// <param name="arg4">Action parameter no. 4, of the type specified in <typeparamref name="T4"/>. This parameter is not null-checked and is forwarded directly to the function.</param>
        /// <param name="arg5">Action parameter no. 5, of the type specified in <typeparamref name="T5"/>. This parameter is not null-checked and is forwarded directly to the function.</param>
        /// <param name="arg6">Action parameter no. 6, of the type specified in <typeparamref name="T6"/>. This parameter is not null-checked and is forwarded directly to the function.</param>
        /// <param name="arg7">Action parameter no. 7, of the type specified in <typeparamref name="T7"/>. This parameter is not null-checked and is forwarded directly to the function.</param>
        /// <param name="arg8">Action parameter no. 8, of the type specified in <typeparamref name="T8"/>. This parameter is not null-checked and is forwarded directly to the function.</param>
        /// <param name="arg9">Action parameter no. 9, of the type specified in <typeparamref name="T9"/>. This parameter is not null-checked and is forwarded directly to the function.</param>
        /// <param name="arg10">Action parameter no. 10, of the type specified in <typeparamref name="T10"/>. This parameter is not null-checked and is forwarded directly to the function.</param>
        /// <param name="arg11">Action parameter no. 11, of the type specified in <typeparamref name="T11"/>. This parameter is not null-checked and is forwarded directly to the function.</param>
        /// <param name="arg12">Action parameter no. 12, of the type specified in <typeparamref name="T12"/>. This parameter is not null-checked and is forwarded directly to the function.</param>
        /// <param name="arg13">Action parameter no. 13, of the type specified in <typeparamref name="T13"/>. This parameter is not null-checked and is forwarded directly to the function.</param>
        /// <param name="arg14">Action parameter no. 14, of the type specified in <typeparamref name="T14"/>. This parameter is not null-checked and is forwarded directly to the function.</param>
        /// <param name="arg15">Action parameter no. 15, of the type specified in <typeparamref name="T15"/>. This parameter is not null-checked and is forwarded directly to the function.</param>
        /// <param name="arg16">Action parameter no. 16, of the type specified in <typeparamref name="T16"/>. This parameter is not null-checked and is forwarded directly to the function.</param>
        /// <param name="cancellationToken">The task's (optional) <see cref="System.Threading.CancellationToken"/>.</param>
        /// <returns>A <see cref="System.Threading.Tasks.Task"/> that can be awaited.</returns>
        public static Task RetryAsync<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16>(Action<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16> action, IRetryPolicy retryPolicy, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6, T7 arg7, T8 arg8, T9 arg9, T10 arg10, T11 arg11, T12 arg12, T13 arg13, T14 arg14, T15 arg15, T16 arg16, CancellationToken cancellationToken = default(CancellationToken))
        {
            return action.WithRetryAsync(retryPolicy, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14, arg15, arg16, cancellationToken);
        }
    }
}
